# Generated by Django 6.0.1 on 2026-01-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web App'), ('mobile', 'Mobile'), ('uiux', 'UI/UX'), ('other', 'Other')], default='web', max_length=50),
        ),
    ]
