# Generated by Django 6.0.1 on 2026-01-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='isFeatured',
        ),
    ]
