# Generated by Django 6.0.1 on 2026-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_content_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='heroImageFile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resumeFile',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
