# Generated by Django 6.0.1 on 2026-01-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_heroimagefile_profile_resumefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='aboutImageFile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
