# Generated by Django 6.0.1 on 2026-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='heroImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resumeUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
