# Generated by Django 6.0.1 on 2026-01-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_aboutimage_alter_profile_heroimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
