# Generated by Django 6.0.1 on 2026-01-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_bio_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stats_exp_years',
            field=models.CharField(blank=True, help_text="Override experience years display (e.g. '5+')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stats_project_count',
            field=models.CharField(blank=True, help_text="Override project count display (e.g. '15+')", max_length=50, null=True),
        ),
    ]
