# Generated by Django 6.0.1 on 2026-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_stats_exp_years_profile_stats_project_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description_id', models.CharField(blank=True, max_length=150)),
                ('short_description_en', models.CharField(blank=True, max_length=150)),
                ('long_description_id', models.TextField(blank=True)),
                ('long_description_en', models.TextField(blank=True)),
                ('aboutImage', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutImageFile', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_id', models.CharField(default='Halo, Saya', max_length=100)),
                ('greeting_en', models.CharField(blank=True, max_length=100)),
                ('roles_id', models.TextField(default='["Pengembang", "Desainer"]')),
                ('roles_en', models.TextField(blank=True, default='[]')),
                ('heroImage', models.CharField(blank=True, max_length=500, null=True)),
                ('heroImageFile', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
    ]
