# Generated by Django 6.0.1 on 2026-01-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_projectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.projectcategory'),
        ),
    ]
