# Generated by Django 6.0.1 on 2026-01-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
