# Generated by Django 6.0.1 on 2026-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_project_new_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
    ]
