# Generated by Django 6.0.1 on 2026-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_blogcategory_project_is_published_project_publish_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq (Llama 3)')], max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
            ],
        ),
    ]
