# Generated by Django 6.0.1 on 2026-01-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_aikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Google Maps Embed URL (iframe src)', null=True),
        ),
    ]
