# Generated by Django 6.0.1 on 2026-01-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenanceMode',
            field=models.BooleanField(default=False),
        ),
    ]
