# Generated by Django 6.0.1 on 2026-01-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sitesettings_maintenancemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_end_time',
            field=models.DateTimeField(blank=True, help_text='Auto turn off maintenance mode after this time', null=True),
        ),
    ]
