# Generated by Django 6.0.1 on 2026-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_sitesettings_maintenance_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq')], default='gemini', max_length=20),
        ),
    ]
