# Generated by Django 6.0.1 on 2026-01-26 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_sitesettings_ai_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='api.project')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
    ]
