# Generated by Django 6.0.1 on 2026-01-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='links',
            new_name='featured_links',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='techStack',
            new_name='tech',
        ),
        migrations.RemoveField(
            model_name='project',
            name='demoUrl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repoUrl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='video_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='greeting',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
    ]
